apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: acs-deploy-check
  annotations:
    task.results.format: application/json
    task.results.type: roxctl-image-scan
    task.results.key: SCAN_OUTPUT
    task.output.location: logs
    task.results.container: step-acs-deploy-check
spec: 
  params:
    - name: message
      type: string
      default: "no message" 
  steps:
  - name: annotate-task
    image: registry.redhat.io/openshift4/ose-cli:4.13@sha256:73df37794ffff7de1101016c23dc623e4990810390ebdabcbbfa065214352c7c
    script: |
      #!/usr/bin/env bash   
      echo "acs-deploy-check $(context.taskRun.name)" 
      oc annotate taskrun $(context.taskRun.name) task.results.format=application/json
      oc annotate taskrun $(context.taskRun.name) task.results.type=roxctl-deployment-check
      oc annotate taskrun $(context.taskRun.name) task.results.key=SCAN_OUTPUT
      oc annotate taskrun $(context.taskRun.name) task.output.location=logs
      oc annotate taskrun $(context.taskRun.name) task.results.container=step-report
  - name: report
    image: registry.redhat.io/openshift4/ose-cli:4.13@sha256:73df37794ffff7de1101016c23dc623e4990810390ebdabcbbfa065214352c7c
    script: |
      #!/usr/bin/env bash 
      cat ./workspace/output/source/acs-deploy-check
  workspaces:
  - description: The git repo will be cloned onto the volume backing this Workspace.
    name: output
   