apiVersion: tekton.dev/v1
kind: Pipeline
metadata: 
  name: pac-pipeline
spec: 
  params: 
    - default: "default message"
      description: Random Param
      name: message
      type: string
  results: 
    - name: ACS_SCAN_OUTPUT
      value: $(tasks.acs-image-scan.results.SCAN_OUTPUT)
  tasks:
    - name: git-clone
      params:
        - name: url
          value:  https://github.com/jduimovich/acs-test
        - name: revision
          value: main
      taskRef:
        name: git-clone 
      workspaces:
        - name: output
          workspace: workspace
    - name: acs-image-scan
      params:
        - name: message
          value: $(params.message)  
      runAfter:
        - git-clone
      taskRef:
        name: acs-image-scan
      workspaces:
        - name: output
          workspace: workspace
    - name: acs-image-check
      params:
        - name: message
          value: $(params.message)  
      runAfter:
        - git-clone
      taskRef:
        name: acs-image-check
      workspaces:
        - name: output
          workspace: workspace
    - name: acs-deploy-check
      params:
        - name: message
          value: $(params.message)  
      runAfter:
        - git-clone
      taskRef:
        name: acs-deploy-check
      workspaces:
        - name: output
          workspace: workspace

