apiVersion: tekton.dev/v1
kind: Pipeline
metadata: 
  name: pac-pipeline-promote
spec: 
  params: 
    - default: "default message"
      description: Random Param
      name: message
      type: string 
  tasks:
    - name: git-clone
      params:
        - name: url
          value:  https://github.com/jduimovich/acs-test
        - name: revision
          value: main
      taskRef:
        name: git-clone 
      workspaces:
        - name: output
          workspace: workspace
    - name: promote-debug 
      params:
        - name: message
          value: "promote-debug "
      runAfter:
        - git-clone
      taskRef:
        name: promote
    - name: promote
      params:
        - name: message
          value: $(params.message)  
      runAfter:
        - promote-debug 
      taskRef:
        name: promote
    - name: promote-after 
      params:
        - name: message
          value: "promote-after "
      runAfter:
        - promote
      taskRef:
        name: promote
      workspaces:
        - name: output
          workspace: workspace
     