apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: promote 
spec: 
  params:
    - name: message
      type: string
      default: "no message" 
  steps:
  - name: annotate-task
    image: registry.redhat.io/openshift4/ose-cli:4.13@sha256:73df37794ffff7de1101016c23dc623e4990810390ebdabcbbfa065214352c7c
    script: |
      #!/usr/bin/env bash 
      curl -L https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 -o ./jq && chmod +x ./jq  
      echo "promote task"
      ls -al 
      echo $(params.message) | ./jq
  workspaces:
  - description: The git repo will be cloned onto the volume backing this Workspace.
    name: output
   